### ISSUE TITLE
Uniswap + Metamask + BSC (Binance smart chain)

### ISSUE THREAD

**Issue by H1l4nd0r** [second-state/how_to_deploy_uniswap#6]
When deploying 

node deploy_uniswap_v2.js

got the error below but the transaction is successful, what is wrong?

here I see success
https://testnet.bscscan.com/tx/0x27125601163a7aeb1a34f06fdeac20606c2b1d53c1346507e9cbe49beb301e3f

but I get this error
...
Data written to file
feeTo is currently set to: 0x0000000000000000000000000000000000000000
feeToSetter is currently set to: 0xc0a4272bb5df52134178Df25d77561CfB17ce407
Deploying ROUTER2 now, please wait ...
0x27125601163a7aeb1a34f06fdeac20606c2b1d53c1346507e9cbe49beb301e3f
Transaction hash: 0x27125601163a7aeb1a34f06fdeac20606c2b1d53c1346507e9cbe49beb301e3f
(node:17063) UnhandledPromiseRejectionWarning: Error: transaction underpriced
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:15:632675
    at t.i.onreadystatechange (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:748948)
    at t.e.dispatchEvent (/root/node_modules/truffle-hdwallet-provider/dist/index.js:1:142373)
    at t._setReadyState (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:753708)
    at t._onHttpResponseEnd (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:756793)
    at IncomingMessage.<anonymous> (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:756051)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:17063) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17063) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Contract address: 0x49985360d54F5C850F04FD0D925ae2762E4ddbEb
0x49985360d54F5C850F04FD0D925ae2762E4ddbEb
Data written to file
Name set to: Wrapped Ether
Symbol set to: WETH
Total Supply set to: 0

**Comment by H1l4nd0r** [comment]
.

**Comment by lorrp1** [comment]
@H1l4nd0r did you figure out how to do it? 
i think there might be an issue with infura too

**Comment by H1l4nd0r** [comment]
> @H1l4nd0r did you figure out how to do it?
> i think there might be an issue with infura too

How did you figured out it''s infura? I've changed rpc endpoint to binance testnet

**Comment by ebinum83** [comment]
Did anyone find out why the feetosetter is set to 0xc0a4272bb5df52134178Df25d77561CfB17ce407. I would like this to be an address that I own

**Comment by H1l4nd0r** [comment]
> Did anyone find out why the feetosetter is set to 0xc0a4272bb5df52134178Df25d77561CfB17ce407. I would like this to be an address that I own

just replace it )
