### ISSUE TITLE
“The contract code couldn't be stored, please check your gas limit“

### ISSUE THREAD

**Issue by 6wukong6** [second-state/how_to_deploy_uniswap#9]
`Deploying Multicall now, please wait ...
0x4114c1e6fd314f7b35d546a53bbccc8e80000e6b842768505a858c2313ce3e06
Transaction hash: 0x4114c1e6fd314f7b35d546a53bbccc8e80000e6b842768505a858c2313ce3e06
Error: The contract code couldn't be stored, please check your gas limit.
    at Object.callback (/root/eth/uniswap-interface/node_modules/web3-core-method/src/index.js:333:46)
    at sendTxCallback (/root/eth/uniswap-interface/node_modules/web3-core-method/src/index.js:484:29)
    at /root/eth/uniswap-interface/node_modules/web3-core-requestmanager/src/index.js:147:9
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:549917
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:140344
    at d (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:206203)
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:206256
    at t.default (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:564796)
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:206574
    at s (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:549761)
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:632708
    at t.i.onreadystatechange (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:748948)
    at t.e.dispatchEvent (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:142373)
    at t._setReadyState (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:753708)
    at t._onHttpResponseEnd (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:756793)
    at IncomingMessage.<anonymous> (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:756051)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:17706) UnhandledPromiseRejectionWarning: Error: The contract code couldn't be stored, please check your gas limit.
    at Object.callback (/root/eth/uniswap-interface/node_modules/web3-core-method/src/index.js:333:46)
    at sendTxCallback (/root/eth/uniswap-interface/node_modules/web3-core-method/src/index.js:484:29)
    at /root/eth/uniswap-interface/node_modules/web3-core-requestmanager/src/index.js:147:9
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:549917
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:140344
    at d (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:206203)
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:206256
    at t.default (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:564796)
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:206574
    at s (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:549761)
    at /root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:632708
    at t.i.onreadystatechange (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:748948)
    at t.e.dispatchEvent (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:1:142373)
    at t._setReadyState (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:753708)
    at t._onHttpResponseEnd (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:756793)
    at IncomingMessage.<anonymous> (/root/eth/uniswap-interface/node_modules/truffle-hdwallet-provider/dist/index.js:15:756051)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:17706) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17706) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Deploy Multicall  or Migrator  contract always report this error, increase gas did not solve the problem, 
any suggestions?

**Comment by aharonhaber** [comment]
I have the same issue.  Tried making gas unlimited on the blockchain - didnt work.

**Comment by 6wukong6** [comment]
> I have the same issue. Tried making gas unlimited on the blockchain - didnt work.

I think the code may need some adjustment, geth upgrade caused incompatibility

**Comment by 6wukong6** [comment]
use eth.getBlock("latest").gasLimit, and use the return gas.

**Comment by 6wukong6** [comment]
//** Please note this is a draft and this code is under heavy development. Not to be used in production **
'use strict';
const fs = require('fs');
const HDWalletProvider = require('truffle-hdwallet-provider');
const async = require('async');

function get_data(_message) {
    return new Promise(function(resolve, reject) {
        fs.readFile('../installation_data.json', (err, data) => {
            if (err) throw err;
            resolve(data);
        });
    });
}

function write_data(_message) {
    return new Promise(function(resolve, reject) {
        fs.writeFile('../installation_data.json', _message, (err) => {
            if (err) throw err;
            console.log('Data written to file');
            resolve();
        });
    });
}

var privateKeys = [];
var URL = "";


(async () => {
    // Read in the configuration information
    var data = await get_data();
    var data_object = JSON.parse(data);
    // Add keys
    console.log("Adding Alice, Bob and Charlie keys ...");
    privateKeys.push(data_object.private_key.alice, data_object.private_key.bob, data_object.private_key.charlie);
    // RPC
    URL = data_object.provider.rpc_endpoint;

    // Web3 - keys and accounts
    const Web3 = require("web3");
    const provider = new HDWalletProvider(privateKeys, URL, 0, 3);
    const web3 = new Web3(provider);
    await web3.eth.net.isListening();
    console.log('Web3 is connected.');
    let accounts = await web3.eth.getAccounts();
    console.log(`accounts: ${JSON.stringify(accounts)}`);
    // -- Uniswap V2
    var uniswapV2Bytecode = data_object.bytecode.uniswap_v2;
    var uniswapV2Abi = data_object.abi.uniswap_v2;
    var uniswapMulticallBytecode = data_object.bytecode.multicall;
    var uniswapMulticallAbi = data_object.abi.multicall;
    var uniswapMigratorBytecode = data_object.bytecode.migrator;
    var uniswapMigratorAbi = data_object.abi.migrator;
    var uniswapRouterBytecode = data_object.bytecode.router;
    var uniswapRouterAbi = data_object.abi.router;
    var uniswapEnsRegistryBytecode = data_object.bytecode.ens_registry;
    var uniswapEnsRegistryAbi = data_object.abi.ens_registry;
    var uniswapUnisocksBytecode = data_object.bytecode.unisocks;
    var uniswapUnisocksAbi = data_object.abi.unisocks;
    var uniswapWETHBytecode = data_object.bytecode.weth;
    var uniswapWETHAbi = data_object.abi.weth;
    var gasRelayHubAddressAbi = data_object.abi.gas_relay_hub_address;
    var gasRelayHubAddressBytecode = data_object.bytecode.gas_relay_hub_address;

    var gas = 7500000



    var uniswapV2 = async function () {

        // Fee to setter account controls this factory forever. Please choose your feeToSetter account carefully
        // Must be secure and preserved; this is paramount
        var _feeToSetter = accounts[2];
        // Uniswap V2
        // V2 Factory Deployment
        console.log("Deploying Uniswap V2 now, please wait ...");

        let uniswapV2;
        uniswapV2 = await web3.eth.sendTransaction({
            from: accounts[2],
            data: uniswapV2Bytecode
        }); // Charlie accounts[2] is the owner
        let uniswapV2Instance = new web3.eth.Contract(uniswapV2Abi, uniswapV2.contractAddress);
        uniswapV2Instance.deploy({
            data: uniswapV2Bytecode,
            arguments: [_feeToSetter]
        })
            .send({
                from: accounts[2],
                gas: gas,
                gasPrice: '30000000000'
            }, function (error, transactionHash) {
                console.log(transactionHash);
            }) 
            .on('error', function (error) {
                console.log(error);
            })
            .on('transactionHash', function (transactionHash) {
                console.log("Transaction hash: " + transactionHash);
            })
            .on('receipt', function (receipt) {
                console.log("Contract address: " + receipt.contractAddress) // contains the new contract address
                data_object.contract_address.uniswap_v2 = receipt.contractAddress;
                let data_to_write = JSON.stringify(data_object, null, 2);
                write_data(data_to_write);
            })
            .then(function (newContractInstance) {
                console.log(newContractInstance.options.address) // instance with the new contract address
                var feeTo = newContractInstance.methods.feeTo().call()
                feeTo.then(function (resultFeeTo) {
                    console.log("feeTo is currently set to: " + resultFeeTo);
                })
                var feeToSetter = newContractInstance.methods.feeToSetter().call()
                feeToSetter.then(function (resultFeeToSetter) {
                    console.log("feeToSetter is currently set to: " + resultFeeToSetter);
                    uniswapWETH();
                })
                
            });
    }

    uniswapV2();

    var uniswapWETH = async function (param, callback) {
        // Uniswap V2 WETH
        // V2 WETH Deployment
        console.log("Deploying WETH now, please wait ...");
        let uniswapWETH;
        uniswapWETH = await web3.eth.sendTransaction({
            from: accounts[2],
            data: uniswapWETHBytecode
        }); // Charlie accounts[2] is the owner
        let uniswapWETHInstance = new web3.eth.Contract(uniswapWETHAbi, uniswapWETH.contractAddress);
        uniswapWETHInstance.deploy({
            data: uniswapWETHBytecode
        })
            .send({
                from: accounts[2],
                gas: gas,
                gasPrice: '30000000000'
            }, function (error, transactionHash) {
                console.log(transactionHash);
            })
            .on('error', function (error) {
                console.log(error);
            })
            .on('transactionHash', function (transactionHash) {
                console.log("Transaction hash: " + transactionHash);
            })
            .on('receipt', function (receipt) {
                console.log("Contract address: " + receipt.contractAddress) // contains the new contract address
                data_object.contract_address.weth = receipt.contractAddress;
                let data_to_write = JSON.stringify(data_object, null, 2);
                write_data(data_to_write);
            })
            .then(function (newContractInstance) {
                console.log(newContractInstance.options.address) // instance with the new contract address
                var name = newContractInstance.methods.name().call()
                name.then(function (resultName) {
                    console.log("Name set to: " + resultName);
                })
                var symbol = newContractInstance.methods.symbol().call()
                symbol.then(function (resultSymbol) {
                    console.log("Symbol set to: " + resultSymbol);
                })
                var totalSupply = newContractInstance.methods.totalSupply().call()
                totalSupply.then(function (resultTotalSupply) {
                    console.log("Total Supply set to: " + resultTotalSupply);
                    uniswapROUTER2();
                })
            });
    }


    var uniswapROUTER2 = async function () {
        // Uniswap V2 ROUTER2
        // V2 ROUTER2 Deployment
        console.log("Deploying ROUTER2 now, please wait ...");
        let uniswapROUTER2;
        uniswapROUTER2 = await web3.eth.sendTransaction({
            from: accounts[2],
            data: uniswapRouterBytecode
        }); // Charlie accounts[2] is the owner
        let uniswapROUTER2Instance = new web3.eth.Contract(uniswapRouterAbi, uniswapROUTER2.contractAddress);
        uniswapROUTER2Instance.deploy({
            data: uniswapRouterBytecode,
            arguments: [data_object.contract_address.uniswap_v2, data_object.contract_address.weth]
        })
            .send({
                from: accounts[2],
                gas: gas,
                gasPrice: '30000000000'
            }, function (error, transactionHash) {
                console.log(transactionHash);
            })
            .on('error', function (error) {
                console.log(error);
            })
            .on('transactionHash', function (transactionHash) {
                console.log("Transaction hash: " + transactionHash);
            })
            .on('receipt', function (receipt) {
                console.log("Contract address: " + receipt.contractAddress) // contains the new contract address
                data_object.contract_address.router = receipt.contractAddress;
                let data_to_write = JSON.stringify(data_object, null, 2);
                write_data(data_to_write);
            })
            .then(function (newContractInstance) {
                console.log(newContractInstance.options.address) // instance with the new contract address
                var factoryVar = newContractInstance.methods.factory().call()
                factoryVar.then(function (resultFactory) {
                    console.log("Router2's factory set to: " + resultFactory);
                })
                var wethVar = newContractInstance.methods.WETH().call()
                wethVar.then(function (resultWeth) {
                    console.log("Router2's WETH set to: " + resultWeth);
                    uniswapMulticall();
                })
            });
    }
    var uniswapMulticall = async function () {
        // Uniswap V2 Multicall
        // V2 Multicall Deployment
        console.log("Deploying Multicall now, please wait ...");
        let uniswapMulticall;
        uniswapMulticall = await web3.eth.sendTransaction({
            from: accounts[2],
            data: uniswapMulticallBytecode
        }); // Charlie accounts[2] is the owner
        let uniswapMulticallInstance = new web3.eth.Contract(uniswapMulticallAbi, uniswapMulticall.contractAddress);
        uniswapMulticallInstance.deploy({
            data: uniswapMulticallBytecode
        })
            .send({
                from: accounts[2],
                gas: gas,
                gasPrice: '30000000000'
            }, function (error, transactionHash) {
                console.log(transactionHash);
            })
            .on('error', function (error) {
                console.log(error);
            })
            .on('transactionHash', function (transactionHash) {
                console.log("Transaction hash: " + transactionHash);
            })
            .on('receipt', function (receipt) {
                console.log("Contract address: " + receipt.contractAddress) // contains the new contract address
                data_object.contract_address.multicall = receipt.contractAddress;
                let data_to_write = JSON.stringify(data_object, null, 2);
                write_data(data_to_write);
            })
            .then(function (newContractInstance) {
                console.log(newContractInstance.options.address) // instance with the new contract address
                uniswapMigrator();
            });
    }
    
    var uniswapMigrator = async function () {
        // Uniswap V2 Migrator
        // V2 Migrator Deployment
        console.log("Deploying Migrator now, please wait ...");
        let uniswapMigrator;
        uniswapMigrator = await web3.eth.sendTransaction({
            from: accounts[2],
            data: uniswapMigratorBytecode
        }); // Charlie accounts[2] is the owner
        let uniswapMigratorInstance = new web3.eth.Contract(uniswapMigratorAbi, uniswapMigrator.contractAddress);
        uniswapMigratorInstance.deploy({
            data: uniswapMigratorBytecode,
            arguments: [data_object.contract_address.uniswap_factory, data_object.contract_address.router]
        })
            .send({
                from: accounts[2],
                gas: gas,
                gasPrice: '30000000000'
            }, function (error, transactionHash) {
                console.log(transactionHash);
            })
            .on('error', function (error) {
                console.log(error);
            })
            .on('transactionHash', function (transactionHash) {
                console.log("Transaction hash: " + transactionHash);
            })
            .on('receipt', function (receipt) {
                console.log("Contract address: " + receipt.contractAddress) // contains the new contract address
                data_object.contract_address.migrator = receipt.contractAddress;
                let data_to_write = JSON.stringify(data_object, null, 2);
                write_data(data_to_write);
            })
            .then(function (newContractInstance) {
                console.log(newContractInstance.options.address) // instance with the new contract address
                ensRegistry();
            });
    }

    var ensRegistry = async function () {
        // V2 ENS registry Deployment
        console.log("Deploying ENS registry now, please wait ...");
        let ensRegistry;
        ensRegistry = await web3.eth.sendTransaction({
            from: accounts[2],
            data: uniswapEnsRegistryBytecode
        }); // Charlie accounts[2] is the owner
        let uniswapEnsRegistryInstance = new web3.eth.Contract(uniswapEnsRegistryAbi, ensRegistry.contractAddress);
        uniswapEnsRegistryInstance.deploy({
            data: uniswapEnsRegistryBytecode,
            arguments: [accounts[2]]
        })
            .send({
                from: accounts[2],
                gas: gas,
                gasPrice: '30000000000'
            }, function (error, transactionHash) {
                console.log(transactionHash);
            })
            .on('error', function (error) {
                console.log(error);
            })
            .on('transactionHash', function (transactionHash) {
                console.log("Transaction hash: " + transactionHash);
            })
            .on('receipt', function (receipt) {
                console.log("Contract address: " + receipt.contractAddress) // contains the new contract address
                data_object.contract_address.ens_registry = receipt.contractAddress;
                let data_to_write = JSON.stringify(data_object, null, 2);
                write_data(data_to_write);
            })
            .then(function (newContractInstance) {
                console.log(newContractInstance.options.address) // instance with the new contract address
                ensRegistry();
            });
    }

    var ensRegistry = async function () {
        // V2 Gas relay hub address
        console.log("Deploying Gas relay hub address contract now, please wait ...");
        let gasRelayHubAddress;
        gasRelayHubAddress = await web3.eth.sendTransaction({
            from: accounts[2],
            data: gasRelayHubAddressBytecode
        }); // Charlie accounts[2] is the owner
        let gasRelayHubAddressInstance = new web3.eth.Contract(gasRelayHubAddressAbi, gasRelayHubAddress.contractAddress);
        gasRelayHubAddressInstance.deploy({
            data: gasRelayHubAddressBytecode
        })
            .send({
                from: accounts[2],
                gas: gas,
                gasPrice: '30000000000'
            }, function (error, transactionHash) {
                console.log(transactionHash);
            })
            .on('error', function (error) {
                console.log(error);
            })
            .on('transactionHash', function (transactionHash) {
                console.log("Transaction hash: " + transactionHash);
            })
            .on('receipt', function (receipt) {
                console.log("Contract address: " + receipt.contractAddress) // contains the new contract address
                data_object.contract_address.gas_relay_hub_address = receipt.contractAddress;
                let data_to_write = JSON.stringify(data_object, null, 2);
                write_data(data_to_write);
            })
            .then(function (newContractInstance) {
                console.log(newContractInstance.options.address) // instance with the new contract address
                writeData();
            });
    }

    var writeData = async function () {
        let data_to_write = JSON.stringify(data_object, null, 2);
        await write_data(data_to_write);
        await provider.engine.stop();
    }



})();
